# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 23:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('buying_power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_asset', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='BuyingPowerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('remaining_money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_resources.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.IntegerField()),
                ('average_cost', models.DecimalField(decimal_places=2, default='0.00', max_digits=6)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_resources.Account')),
            ],
        ),
        migrations.CreateModel(
            name='HoldingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('shares', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_resources.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('company_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='default', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TotalAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_asset', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_resources.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shares', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_resources.Account')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_resources.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='holdinghistory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_resources.Stock'),
        ),
        migrations.AddField(
            model_name='hold',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='global_resources.Stock'),
        ),
        migrations.AddField(
            model_name='account',
            name='watched_stocks',
            field=models.ManyToManyField(to='global_resources.Stock'),
        ),
    ]
