# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-03 23:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingpowerhistory',
            name='date',
            field=models.DateField(default=datetime.date(2017, 12, 3)),
        ),
        migrations.AlterField(
            model_name='holdinghistory',
            name='date',
            field=models.DateField(default=datetime.date(2017, 12, 3)),
        ),
        migrations.AlterField(
            model_name='totalasset',
            name='date',
            field=models.DateField(default=datetime.date(2017, 12, 3)),
        ),
    ]
